## 00. pytorch fundemetals

In [1]:
print('hello I am excited to learn py' )

hello I am excited to learn py


In [2]:
import torch
print(torch.__version__)

2.1.2


# introduction to tensors 

## creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

# everything works from tensors building blocks of nn
## create using torch.tensor

In [4]:
scalar.ndim
#scalar has no dim ndim shows dim
#ndim is atribute of scalar object 

0

In [6]:
# get tensor item back 
scalar.item()


7

In [7]:
# vector
vector = torch.tensor([7,7])
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

shape is the formation of the dimentions 
and ndim is the num of dim

In [9]:
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [13]:
MATRIX.ndim


2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
MATRIX[0]

tensor([1, 2])

In [15]:
MATRIX[1]

tensor([3, 4])

In [18]:
TENSOR = torch.tensor([[[1, 2, 4],[3,4,5], [8,9,0]]])
TENSOR

tensor([[[1, 2, 4],
         [3, 4, 5],
         [8, 9, 0]]])

In [17]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0].shape

torch.Size([3, 3])

### Random Tensors

random tensors are important becuase they start with random numbers
look at data
update rand num
look at data
repeat

In [24]:
# create random tensor
random_ten = torch.rand(3,4)
random_ten

tensor([[0.9001, 0.2155, 0.9833, 0.0327],
        [0.4548, 0.1915, 0.8373, 0.0662],
        [0.6451, 0.5937, 0.4081, 0.7509]])

torch.rand creates rand int between 0,1

In [29]:
random_img_size_ten = torch.rand(224, 224, 3)
random_img_size_ten.shape, random_img_size_ten.ndim

(torch.Size([224, 224, 3]), 3)

In [33]:
zeros_ten = torch.zeros(size=(3, 4))
zeros_ten* random_ten

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### multiply matrix needs to be same shape
have not gotton to dot product yet

In [34]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

torch.zeros for zeros
torch.ones for ones
torch.rand for rand int 

torch.shape for shape 
torch.ndim for dim
torch.items for items

## creating a range of tensors and tensors-like

In [35]:
# use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# create tensors like 
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
zero_to_three = torch.arange(0,3, .4)
zero_to_three
#if not even stops at the last increment before

tensor([0.0000, 0.4000, 0.8000, 1.2000, 1.6000, 2.0000, 2.4000, 2.8000])

### stops at the last increment before

## datatype

In [53]:
float32 = torch.tensor(3., 
                       device=None, 
                       requires_grad=False)

float32.dtype

torch.float32

computer will store differnt dtypes on different formats
can calculate faster on num that take memmory

one of the three big ml errors with pytorch and DL

1. Tensors not right dt
2. tensors not right shape
3. tensors not on device

In [51]:
float_16_tensor = float32.type(torch.float16)
float_16_tensor.dtype, float32.dtype

(torch.float16, torch.int64)

### getting information from our tensors 
shape = .shape
type =  .dtype
device = .device

In [55]:
rand = torch.rand(size=(3,4))
rand.dtype, rand.device, rand.shape

(torch.float32, device(type='cpu'), torch.Size([3, 4]))

## manipulating tensors
tensor operations:

* addition 
* subtraction 
* multiplecation (element wise)
* division 
* matrix mult

two main rules when matmul
- inner dim must match
- resulting matrix will be shap of outer dim

In [60]:
# create a tensor 
tens = torch.tensor([1,2,3])
tens + 10, tens - 1

(tensor([11, 12, 13]), tensor([0, 1, 2]))

In [61]:
tens * 10, tens/.1

(tensor([10, 20, 30]), tensor([10., 20., 30.]))

### pytorch has inbuilt funcions

In [63]:
torch.mul(tens, 10), torch.sub(tens, -1)

(tensor([10, 20, 30]), tensor([2, 3, 4]))

### MATMUL

- matmul involes combining elements (dot product)
- mxn * nxp 

In [67]:
one_to_6 = torch.arange(1,7).reshape(-1, 3)
seven_to_tweleve = torch.arange(7, 13).reshape(3, -1)
final = torch.matmul(one_to_6, seven_to_tweleve)
final

tensor([[ 58,  64],
        [139, 154]])

In [69]:
one_to_6 = torch.arange(1,7).reshape(-1, 3)
seven_to_tweleve = torch.arange(7, 13).reshape(-1, 3).T
final = torch.matmul(one_to_6, seven_to_tweleve)
final

tensor([[ 50,  68],
        [122, 167]])

### one of the most common errors in dl are shape errors
.T will transpose the matrix

### find mim max mean sum & more agrigation methods

In [76]:
agri_ten = torch.rand(3,4) *100
agri_ten = agri_ten.floor()
agri_ten.max(), agri_ten.min(), agri_ten.mean(), agri_ten.sum()

(tensor(97.), tensor(2.), tensor(57.2500), tensor(687.))

In [77]:
agri_ten.argmax(), agri_ten.argmin()

(tensor(5), tensor(10))

### reshape, stack, squeeze, unsqueeze

- reshape 
- stack concate tensors along specificed dim 
- squeeze removes all 1 dim from tensor
- Permute - return a view of the input with dim permuted

In [78]:
import torch

In [93]:
one_nine = torch.arange(1,11)
one_nine

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
#add dim
one_nine_res = one_nine.reshape(5, 2)
one_nine_res

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [106]:
z = one_nine.view(1, 10).squeeze()
z, z.shape
#chaning a view changes orginal because stored in memory 

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [111]:
stack = torch.stack((z,z,z,z), dim=-2)
stack, stack.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 torch.Size([4, 10]))

In [116]:
un_one_nine = one_nine.unsqueeze(dim=0)
un_one_nine

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [117]:
#torch.permute rearagnes dim in target order
#returns view 
#takes dim array

In [119]:
X = torch.randn(7, 2, 5)


In [122]:
X = X.permute(1,2,0)
X.shape
# all of these can be a method or a function from torch that takes in the tensor as a arg

X_i = torch.rand(size=(224,224,3))
X_n = X_i.permute(2,0,1)
X_n.shape

torch.Size([3, 224, 224])

### Indexing on tensors
Similar to numpy

In [132]:
inX = torch.arange(1,10).reshape(1,3,3)
inX.shape, inX[0]

(torch.Size([1, 3, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [137]:
inX[0][:, 0], inX[0][2][2]

(tensor([1, 4, 7]), tensor(9))

In [138]:
inX[:, :, 1]

tensor([[2, 5, 8]])

In [139]:
inX[:,1,1]

tensor([5])

In [142]:
inX[0,0]

tensor([1, 2, 3])

In [145]:
inX[0,2,2], inX[0,:,2]

(tensor(9), tensor([3, 6, 9]))

### torch and numpy
torch interacts with numpy

torch.from_numpy
torch.tensor().numpy

In [148]:
import numpy as np
import torch

array = np.arange(1,8)
Xn = torch.from_numpy(array)
aryT = torch.tensor(Xn).numpy()
Xn, aryT

/var/folders/2t/2y0f_lxd6w3806pjj2pppbx80000gn/T/ipykernel_3616/3684075708.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  aryT = torch.tensor(Xn).numpy()


(tensor([1, 2, 3, 4, 5, 6, 7]), array([1, 2, 3, 4, 5, 6, 7]))

In [151]:
# change value of array
array += 2
array, Xn

(array([ 5,  6,  7,  8,  9, 10, 11]), tensor([ 5,  6,  7,  8,  9, 10, 11]))

### Torch Reproducibility (random out of random)
set rand seed

In [158]:
randA = torch.rand(3,4)
randB = torch.rand(3,4)

print(randA == randB)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [160]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
randC = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
randD = torch.rand(3,4)

print(randC == randD)
# torch.manual_seed() applies to first rng event 
# google colab has free gpu but apparently gpu gets better

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### working with gpu

In [161]:
torch.cuda.is_available()


False

In [162]:
# can set up device
device = "cuda" if torch.cuda.is_available() else "cpu"

In [163]:
# puting tensors/models on gpu
# using gpu results in faster calculations
tensor = torch.arange(1,4)
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# to fix goig from gpu tensor to numpy tensor cal .cpu then .to_numpy()